version: '2'
services:
    tsm-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/tsm/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=tsm
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
